// Builds dist/ from src/tokens.json (the ELEO design system's token file):
//   tokens.css  every token as a CSS variable; light by default, dark under the OS preference unless
//               data-theme="light", and on any element with data-theme="dark" (or "light").
//   index.js    the same tokens as data, for code that can't read CSS (exports, canvas, native).
import { readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync } from 'node:fs';

const t = JSON.parse(readFileSync('src/tokens.json', 'utf8'));
const [light, dark] = t.color.themes.map((th) => th.id);
const themed = [...t.color.tokens, ...(t.shadow?.tokens ?? [])];
const fixed = ['spacing', 'radius', 'stroke', 'dash', 'marker'].flatMap((f) => t[f]?.tokens ?? []);
const value = (tok, theme) => (typeof tok.value === 'object' ? tok.value[theme] ?? tok.value[light] : tok.value);
const vars = (toks, theme, indent) => toks.map((tok) => `${indent}--${tok.name}: ${value(tok, theme)};`).join('\n');

const css = `/* Generated by @eleoptics/tokens from the ELEO design system's tokens.json. Do not edit by hand.
   Plain hex values: the plot renderers read them with getComputedStyle. */
:root, [data-theme="${light}"] {
  color-scheme: ${light};
${vars(themed, light, '  ')}
}
:root {
${vars(fixed, light, '  ')}
  --font-sans: ${t.type.families.sans};
  --font-mono: ${t.type.families.mono};
}
@media (prefers-color-scheme: ${dark}) {
  :root:not([data-theme="${light}"]) {
  color-scheme: ${dark};
${vars(themed, dark, '  ')}
  }
}
[data-theme="${dark}"] {
  color-scheme: ${dark};
${vars(themed, dark, '  ')}
}
`;

const data = {
  themes: t.color.themes.map((th) => th.id),
  color: Object.fromEntries(themed.map((tok) => [tok.name, Object.fromEntries(t.color.themes.map((th) => [th.id, value(tok, th.id)]))])),
  size: Object.fromEntries(fixed.map((tok) => [tok.name, tok.value])),
  font: t.type.families,
  type: t.type.groups,
};

rmSync('dist', { recursive: true, force: true });
mkdirSync('dist');
writeFileSync('dist/tokens.css', css);
writeFileSync('dist/index.js', `// Generated by @eleoptics/tokens. Do not edit by hand.\nexport default ${JSON.stringify(data, null, 2)};\n`);
copyFileSync('src/index.d.ts', 'dist/index.d.ts');
copyFileSync('src/tokens.json', 'dist/tokens.json');
